
logging:
  level:
    ROOT: INFO
    com.snowj: INFO

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/VolunteerRecruitDB?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=UTC
    username:
    password:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  # spring.activiti.check-process-definitions=false
mybatis:
  # type-aliases-package: edu.cn.cpu.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/auto/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8000
