package edu.cn.cpu.domain.auto;

public class Tblapply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblApply.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblApply.VolunteerNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long volunteernumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblApply.ProgramNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long programnumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblApply.ApplyState
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Integer applystate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblApply.id
     *
     * @return the value of tblApply.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblApply.id
     *
     * @param id the value for tblApply.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblApply.VolunteerNumber_id
     *
     * @return the value of tblApply.VolunteerNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getVolunteernumberId() {
        return volunteernumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblApply.VolunteerNumber_id
     *
     * @param volunteernumberId the value for tblApply.VolunteerNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setVolunteernumberId(Long volunteernumberId) {
        this.volunteernumberId = volunteernumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblApply.ProgramNumber_id
     *
     * @return the value of tblApply.ProgramNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getProgramnumberId() {
        return programnumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblApply.ProgramNumber_id
     *
     * @param programnumberId the value for tblApply.ProgramNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setProgramnumberId(Long programnumberId) {
        this.programnumberId = programnumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblApply.ApplyState
     *
     * @return the value of tblApply.ApplyState
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Integer getApplystate() {
        return applystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblApply.ApplyState
     *
     * @param applystate the value for tblApply.ApplyState
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setApplystate(Integer applystate) {
        this.applystate = applystate;
    }
}