package edu.cn.cpu.domain.auto;

public class Tbldiseasetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblDiseaseType.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblDiseaseType.DiseaseType
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private String diseasetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblDiseaseType.id
     *
     * @return the value of tblDiseaseType.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblDiseaseType.id
     *
     * @param id the value for tblDiseaseType.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblDiseaseType.DiseaseType
     *
     * @return the value of tblDiseaseType.DiseaseType
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public String getDiseasetype() {
        return diseasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblDiseaseType.DiseaseType
     *
     * @param diseasetype the value for tblDiseaseType.DiseaseType
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setDiseasetype(String diseasetype) {
        this.diseasetype = diseasetype == null ? null : diseasetype.trim();
    }
}