package edu.cn.cpu.domain.auto;

public class Tblpp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblPP.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblPP.ProgramNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long programnumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblPP.PromulgatorNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long promulgatornumberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblPP.id
     *
     * @return the value of tblPP.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblPP.id
     *
     * @param id the value for tblPP.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblPP.ProgramNumber_id
     *
     * @return the value of tblPP.ProgramNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getProgramnumberId() {
        return programnumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblPP.ProgramNumber_id
     *
     * @param programnumberId the value for tblPP.ProgramNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setProgramnumberId(Long programnumberId) {
        this.programnumberId = programnumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblPP.PromulgatorNumber_id
     *
     * @return the value of tblPP.PromulgatorNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getPromulgatornumberId() {
        return promulgatornumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblPP.PromulgatorNumber_id
     *
     * @param promulgatornumberId the value for tblPP.PromulgatorNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setPromulgatornumberId(Long promulgatornumberId) {
        this.promulgatornumberId = promulgatornumberId;
    }
}