package edu.cn.cpu.domain.auto;

public class Tbluser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblUser.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblUser.UserName
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblUser.UserPwd
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblUser.VolunteerNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long volunteernumberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblUser.PromulgatorNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    private Long promulgatornumberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblUser.id
     *
     * @return the value of tblUser.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblUser.id
     *
     * @param id the value for tblUser.id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblUser.UserName
     *
     * @return the value of tblUser.UserName
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblUser.UserName
     *
     * @param username the value for tblUser.UserName
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblUser.UserPwd
     *
     * @return the value of tblUser.UserPwd
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblUser.UserPwd
     *
     * @param userpwd the value for tblUser.UserPwd
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblUser.VolunteerNumber_id
     *
     * @return the value of tblUser.VolunteerNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getVolunteernumberId() {
        return volunteernumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblUser.VolunteerNumber_id
     *
     * @param volunteernumberId the value for tblUser.VolunteerNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setVolunteernumberId(Long volunteernumberId) {
        this.volunteernumberId = volunteernumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblUser.PromulgatorNumber_id
     *
     * @return the value of tblUser.PromulgatorNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Long getPromulgatornumberId() {
        return promulgatornumberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblUser.PromulgatorNumber_id
     *
     * @param promulgatornumberId the value for tblUser.PromulgatorNumber_id
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setPromulgatornumberId(Long promulgatornumberId) {
        this.promulgatornumberId = promulgatornumberId;
    }
}