package edu.cn.cpu.domain.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TblvolunteerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public TblvolunteerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberIsNull() {
            addCriterion("VolunteerNumber is null");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberIsNotNull() {
            addCriterion("VolunteerNumber is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberEqualTo(String value) {
            addCriterion("VolunteerNumber =", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberNotEqualTo(String value) {
            addCriterion("VolunteerNumber <>", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberGreaterThan(String value) {
            addCriterion("VolunteerNumber >", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberGreaterThanOrEqualTo(String value) {
            addCriterion("VolunteerNumber >=", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberLessThan(String value) {
            addCriterion("VolunteerNumber <", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberLessThanOrEqualTo(String value) {
            addCriterion("VolunteerNumber <=", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberLike(String value) {
            addCriterion("VolunteerNumber like", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberNotLike(String value) {
            addCriterion("VolunteerNumber not like", value, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberIn(List<String> values) {
            addCriterion("VolunteerNumber in", values, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberNotIn(List<String> values) {
            addCriterion("VolunteerNumber not in", values, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberBetween(String value1, String value2) {
            addCriterion("VolunteerNumber between", value1, value2, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernumberNotBetween(String value1, String value2) {
            addCriterion("VolunteerNumber not between", value1, value2, "volunteernumber");
            return (Criteria) this;
        }

        public Criteria andVolunteernameIsNull() {
            addCriterion("VolunteerName is null");
            return (Criteria) this;
        }

        public Criteria andVolunteernameIsNotNull() {
            addCriterion("VolunteerName is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteernameEqualTo(String value) {
            addCriterion("VolunteerName =", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameNotEqualTo(String value) {
            addCriterion("VolunteerName <>", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameGreaterThan(String value) {
            addCriterion("VolunteerName >", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameGreaterThanOrEqualTo(String value) {
            addCriterion("VolunteerName >=", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameLessThan(String value) {
            addCriterion("VolunteerName <", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameLessThanOrEqualTo(String value) {
            addCriterion("VolunteerName <=", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameLike(String value) {
            addCriterion("VolunteerName like", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameNotLike(String value) {
            addCriterion("VolunteerName not like", value, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameIn(List<String> values) {
            addCriterion("VolunteerName in", values, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameNotIn(List<String> values) {
            addCriterion("VolunteerName not in", values, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameBetween(String value1, String value2) {
            addCriterion("VolunteerName between", value1, value2, "volunteername");
            return (Criteria) this;
        }

        public Criteria andVolunteernameNotBetween(String value1, String value2) {
            addCriterion("VolunteerName not between", value1, value2, "volunteername");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("Sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("Sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("Sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("Sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("Sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("Sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("Sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("Sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("Sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("Sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("Sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("Sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("Sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("Sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("Birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("Birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("Birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("Birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("Birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("Birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdIsNull() {
            addCriterion("DiseaseType_id is null");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdIsNotNull() {
            addCriterion("DiseaseType_id is not null");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdEqualTo(Long value) {
            addCriterion("DiseaseType_id =", value, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdNotEqualTo(Long value) {
            addCriterion("DiseaseType_id <>", value, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdGreaterThan(Long value) {
            addCriterion("DiseaseType_id >", value, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("DiseaseType_id >=", value, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdLessThan(Long value) {
            addCriterion("DiseaseType_id <", value, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdLessThanOrEqualTo(Long value) {
            addCriterion("DiseaseType_id <=", value, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdIn(List<Long> values) {
            addCriterion("DiseaseType_id in", values, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdNotIn(List<Long> values) {
            addCriterion("DiseaseType_id not in", values, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdBetween(Long value1, Long value2) {
            addCriterion("DiseaseType_id between", value1, value2, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasetypeIdNotBetween(Long value1, Long value2) {
            addCriterion("DiseaseType_id not between", value1, value2, "diseasetypeId");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailIsNull() {
            addCriterion("DiseaseDetail is null");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailIsNotNull() {
            addCriterion("DiseaseDetail is not null");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailEqualTo(String value) {
            addCriterion("DiseaseDetail =", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailNotEqualTo(String value) {
            addCriterion("DiseaseDetail <>", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailGreaterThan(String value) {
            addCriterion("DiseaseDetail >", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailGreaterThanOrEqualTo(String value) {
            addCriterion("DiseaseDetail >=", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailLessThan(String value) {
            addCriterion("DiseaseDetail <", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailLessThanOrEqualTo(String value) {
            addCriterion("DiseaseDetail <=", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailLike(String value) {
            addCriterion("DiseaseDetail like", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailNotLike(String value) {
            addCriterion("DiseaseDetail not like", value, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailIn(List<String> values) {
            addCriterion("DiseaseDetail in", values, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailNotIn(List<String> values) {
            addCriterion("DiseaseDetail not in", values, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailBetween(String value1, String value2) {
            addCriterion("DiseaseDetail between", value1, value2, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andDiseasedetailNotBetween(String value1, String value2) {
            addCriterion("DiseaseDetail not between", value1, value2, "diseasedetail");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("Tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("Tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("Tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("Tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("Tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("Tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("Tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("Tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("Tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("Tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("Tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("Tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("Tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("Tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("Address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("Address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("Address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("Address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("Address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("Address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("Address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("Address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("Address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("Address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("Address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("Address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("Address not between", value1, value2, "address");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblVolunteer
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 05 14:02:57 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}