package edu.cn.cpu.repository.auto;

import edu.cn.cpu.domain.auto.Tblpp;
import edu.cn.cpu.domain.auto.TblppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    long countByExample(TblppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByExample(TblppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insert(Tblpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insertSelective(Tblpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    List<Tblpp> selectByExample(TblppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    Tblpp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tblpp record, @Param("example") TblppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExample(@Param("record") Tblpp record, @Param("example") TblppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKeySelective(Tblpp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblPP
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKey(Tblpp record);
}