package edu.cn.cpu.repository.auto;

import edu.cn.cpu.domain.auto.Tblprogram;
import edu.cn.cpu.domain.auto.TblprogramExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblprogramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    long countByExample(TblprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByExample(TblprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insert(Tblprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insertSelective(Tblprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    List<Tblprogram> selectByExample(TblprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    Tblprogram selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tblprogram record, @Param("example") TblprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExample(@Param("record") Tblprogram record, @Param("example") TblprogramExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKeySelective(Tblprogram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblProgram
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKey(Tblprogram record);
}