package edu.cn.cpu.repository.auto;

import edu.cn.cpu.domain.auto.Tbluser;
import edu.cn.cpu.domain.auto.TbluserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbluserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    long countByExample(TbluserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByExample(TbluserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insert(Tbluser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insertSelective(Tbluser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    List<Tbluser> selectByExample(TbluserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    Tbluser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tbluser record, @Param("example") TbluserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExample(@Param("record") Tbluser record, @Param("example") TbluserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKeySelective(Tbluser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblUser
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKey(Tbluser record);
}