package edu.cn.cpu.repository.auto;

import edu.cn.cpu.domain.auto.Tblvolunteer;
import edu.cn.cpu.domain.auto.TblvolunteerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblvolunteerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    long countByExample(TblvolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByExample(TblvolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insert(Tblvolunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int insertSelective(Tblvolunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    List<Tblvolunteer> selectByExample(TblvolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    Tblvolunteer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Tblvolunteer record, @Param("example") TblvolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByExample(@Param("record") Tblvolunteer record, @Param("example") TblvolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKeySelective(Tblvolunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tblVolunteer
     *
     * @mbg.generated Thu Dec 05 14:02:57 CST 2019
     */
    int updateByPrimaryKey(Tblvolunteer record);
}